"use client";

import { useMemo, useState } from "react";
import { Check, ChevronRight, FileDown, FlaskConical, UserRound, ClipboardList, TestTubes, BadgeCheck } from "lucide-react";
import type { Locale } from "@/lib/i18n";

const copy = {
  en:{title:"Try the MEDISOFT workflow",body:"Use fictional data to move a laboratory order from patient registration to a validated report.",steps:["Patient","Order","Results","Report"],next:"Continue",back:"Back",new:"Start again",patient:"Demo patient",notice:"Simulation only — no real patient data",tests:"Selected analyses",result:"Enter sample results",report:"Validated laboratory report",ready:"Ready to validate",complete:"Report ready",download:"Preview PDF",name:"Mira Demo",dob:"14 May 1992",id:"MED-00042"},
  sq:{title:"Provoni procesin MEDISOFT",body:"Përdorni të dhëna fiktive për të kaluar një analizë nga regjistrimi te raporti i validuar.",steps:["Pacienti","Analizat","Rezultatet","Raporti"],next:"Vazhdo",back:"Kthehu",new:"Fillo përsëri",patient:"Pacient demonstrues",notice:"Vetëm simulim — pa të dhëna reale",tests:"Analizat e zgjedhura",result:"Vendosni rezultatet",report:"Raport laboratorik i validuar",ready:"Gati për validim",complete:"Raporti është gati",download:"Shiko PDF",name:"Mira Demo",dob:"14 Maj 1992",id:"MED-00042"}
};

export function DemoWorkflow({ locale }: { locale: Locale }) {
  const t=copy[locale]; const [step,setStep]=useState(0); const [glucose,setGlucose]=useState("92"); const [hb,setHb]=useState("13.8");
  const content=useMemo(()=>[
    <div key="p" className="grid gap-4 sm:grid-cols-2"><Field label={locale==='sq'?'Emri i plotë':'Full name'} value={t.name}/><Field label={locale==='sq'?'ID e pacientit':'Patient ID'} value={t.id}/><Field label={locale==='sq'?'Datëlindja':'Date of birth'} value={t.dob}/><Field label={locale==='sq'?'Gjinia':'Sex'} value={locale==='sq'?'Femër':'Female'}/></div>,
    <div key="o"><p className="mb-4 text-sm font-semibold">{t.tests}</p><div className="grid gap-3 sm:grid-cols-2">{[["Complete blood count","EDTA · Hematology"],["Glucose","Serum · Biochemistry"],["C-reactive protein","Serum · Immunology"]].map((x,i)=><div key={x[0]} className="flex items-start gap-3 rounded-2xl border border-line bg-white p-4"><span className="grid size-6 place-items-center rounded-md bg-teal text-white"><Check size={14}/></span><div><p className="text-sm font-semibold">{x[0]}</p><p className="mt-1 text-xs text-muted">{x[1]}</p></div>{i===1&&<span className="ml-auto rounded-full bg-[#fff0e7] px-2 py-1 text-[10px] text-coral">Priority</span>}</div>)}</div></div>,
    <div key="r"><div className="mb-4 flex items-center justify-between"><p className="text-sm font-semibold">{t.result}</p><span className="rounded-full bg-[#fff0e7] px-3 py-1 text-xs font-medium text-coral">{t.ready}</span></div><div className="overflow-hidden rounded-2xl border border-line bg-white"><div className="grid grid-cols-[1fr_110px_100px] bg-[#f3f7f5] px-4 py-3 text-[10px] font-bold uppercase tracking-wider text-muted"><span>Analysis</span><span>Result</span><span>Range</span></div><ResultRow name="Glucose" value={glucose} onChange={setGlucose} unit="mg/dL" range="70–99"/><ResultRow name="Hemoglobin" value={hb} onChange={setHb} unit="g/dL" range="12–16"/><ResultRow name="CRP" value="2.4" unit="mg/L" range="0–5"/></div></div>,
    <div key="f" className="rounded-2xl border border-line bg-white p-6"><div className="flex items-start justify-between border-b border-line pb-5"><div><p className="text-xs font-bold tracking-widest text-teal">MEDISOFT LAB</p><h3 className="mt-2 text-xl font-semibold">{t.report}</h3></div><span className="grid size-10 place-items-center rounded-full bg-mint text-teal"><BadgeCheck size={21}/></span></div><div className="grid gap-5 py-5 text-sm sm:grid-cols-3"><div><p className="text-xs text-muted">Patient</p><p className="mt-1 font-medium">{t.name}</p></div><div><p className="text-xs text-muted">Order</p><p className="mt-1 font-mono font-medium">MS-2049</p></div><div><p className="text-xs text-muted">Status</p><p className="mt-1 font-medium text-teal">{t.complete}</p></div></div><button className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white"><FileDown size={16}/>{t.download}</button></div>
  ],[step,glucose,hb,locale,t]);
  const icons=[UserRound,ClipboardList,TestTubes,BadgeCheck];
  return <div className="mx-auto max-w-5xl"><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><span className="rounded-full bg-mint px-3 py-1.5 text-xs font-medium text-teal">{t.notice}</span><span className="font-mono text-xs text-muted">Order #MS-2049</span></div><div className="grid overflow-hidden rounded-[28px] border border-line bg-white shadow-[0_24px_70px_rgba(23,53,58,.1)] lg:grid-cols-[240px_1fr]"><aside className="bg-ink p-5 text-white"><div className="mb-8 flex items-center gap-2 font-semibold"><FlaskConical size={20} className="text-[#70d6c2]"/>Lab workflow</div><div className="grid gap-2">{t.steps.map((label,i)=>{const Icon=icons[i];return <button key={label} onClick={()=>i<=step&&setStep(i)} className={`flex items-center gap-3 rounded-xl p-3 text-left text-sm ${step===i?'bg-white text-ink':i<step?'text-[#8ae0d0]':'text-white/45'}`}><span className={`grid size-8 place-items-center rounded-lg ${step===i?'bg-mint text-teal':'bg-white/8'}`}>{i<step?<Check size={16}/>:<Icon size={16}/>}</span>{label}</button>})}</div></aside><section className="min-h-[440px] p-5 sm:p-8"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-widest text-teal">{locale==='sq'?`Hapi ${step+1} nga 4`:`Step ${step+1} of 4`}</p><h2 className="mt-2 text-2xl font-semibold">{t.steps[step]}</h2></div>{content[step]}<div className="mt-9 flex items-center justify-between border-t border-line pt-5"><button onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0} className="rounded-full px-5 py-2.5 text-sm font-semibold disabled:opacity-30">{t.back}</button>{step<3?<button onClick={()=>setStep(step+1)} className="inline-flex items-center gap-2 rounded-full bg-teal px-6 py-3 text-sm font-semibold text-white">{t.next}<ChevronRight size={16}/></button>:<button onClick={()=>setStep(0)} className="rounded-full bg-teal px-6 py-3 text-sm font-semibold text-white">{t.new}</button>}</div></section></div></div>;
}

function Field({label,value}:{label:string;value:string}){return <label className="block text-xs font-medium text-muted">{label}<input value={value} readOnly className="mt-2 w-full rounded-xl border border-line bg-white px-4 py-3 text-sm font-medium text-ink outline-none"/></label>}
function ResultRow({name,value,unit,range,onChange}:{name:string;value:string;unit:string;range:string;onChange?:(v:string)=>void}){return <div className="grid grid-cols-[1fr_110px_100px] items-center border-t border-line px-4 py-3 text-sm"><span className="font-medium">{name}<span className="ml-2 text-xs text-muted">{unit}</span></span><input className="w-20 rounded-lg border border-line px-2 py-1.5 font-mono outline-none focus:border-teal" value={value} onChange={e=>onChange?.(e.target.value)} readOnly={!onChange}/><span className="text-xs text-muted">{range}</span></div>}
