import Link from "next/link";
import { ArrowRight, Check, ShieldCheck, UserRound, ClipboardList, TestTubes, SlidersHorizontal, FileText, CreditCard, MoveRight, LockKeyhole, History, Cloud, BadgeCheck } from "lucide-react";
import type { Dictionary, Locale } from "@/lib/i18n";
import { Header } from "./header";
import { Footer } from "./footer";
import { DashboardPreview } from "./dashboard-preview";

const featureIcons = [UserRound,ClipboardList,TestTubes,SlidersHorizontal,FileText,CreditCard];
const securityIcons = [LockKeyhole,History,Cloud,BadgeCheck];

export function HomePage({ locale, dict }: { locale: Locale; dict: Dictionary }) {
  return <main className="bg-ivory text-ink"><Header locale={locale} dict={dict}/>
    <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-24 pt-16 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:pb-32 lg:pt-24"><div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-teal/15 bg-white px-3.5 py-2 text-xs font-semibold uppercase tracking-wide text-teal shadow-sm"><ShieldCheck size={15}/>{dict.hero.eyebrow}</div><h1 className="max-w-2xl text-5xl font-semibold leading-[1.03] tracking-[-0.045em] sm:text-6xl lg:text-7xl">{dict.hero.title} <span className="text-teal">{dict.hero.accent}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate">{dict.hero.body}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={`/${locale}/contact`} className="inline-flex items-center justify-center gap-2 rounded-full bg-teal px-6 py-3.5 font-semibold text-white shadow-[0_12px_30px_rgba(11,116,111,.22)]">{dict.hero.primary}<ArrowRight size={17}/></Link><Link href={`/${locale}/demo`} className="inline-flex items-center justify-center rounded-full border border-line bg-white px-6 py-3.5 font-semibold">{dict.hero.secondary}</Link></div><p className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate">{[dict.hero.trust1,dict.hero.trust2,dict.hero.trust3].map(x=><span key={x} className="flex gap-1.5"><Check size={14} className="text-teal"/>{x}</span>)}</p></div><DashboardPreview dict={dict}/></section>

    <section className="border-y border-line bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-28"><div><p className="eyebrow">{dict.problem.eyebrow}</p><h2 className="section-title">{dict.problem.title}</h2><p className="section-copy">{dict.problem.body}</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-[#eeded9] bg-[#fff9f7] p-6"><p className="mb-6 text-xs font-bold uppercase tracking-widest text-coral">{dict.problem.before}</p><div className="grid gap-3">{dict.problem.items.map(x=><p key={x} className="flex items-center gap-3 text-sm text-slate"><span className="size-1.5 rounded-full bg-coral"/>{x}</p>)}</div><p className="mt-7 rounded-xl bg-white px-4 py-3 text-xs text-muted">{dict.problem.beforeFlow}</p></div><div className="rounded-3xl bg-ink p-6 text-white"><p className="mb-6 text-xs font-bold uppercase tracking-widest text-[#7bd7c7]">{dict.problem.after}</p><div className="grid gap-4"><p className="text-2xl font-semibold leading-snug">One patient record connects every step.</p><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[88%] rounded-full bg-[#70d6c2]"/></div><div className="flex justify-between text-[10px] text-white/50"><span>Order</span><span>Sample</span><span>Result</span><span>Report</span></div></div><p className="mt-7 rounded-xl bg-white/8 px-4 py-3 text-xs text-white/60">{dict.problem.afterFlow}</p></div></div></div></section>

    <section id="features" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="max-w-2xl"><p className="eyebrow">{dict.features.eyebrow}</p><h2 className="section-title">{dict.features.title}</h2><p className="section-copy">{dict.features.body}</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{dict.features.items.map((item,i)=>{const Icon=featureIcons[i];return <article key={item.title} className="group rounded-3xl border border-line bg-white p-7 transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_50px_rgba(23,53,58,.08)]"><span className="grid size-11 place-items-center rounded-2xl bg-mint text-teal"><Icon size={21}/></span><h3 className="mt-7 text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate">{item.body}</p><Link href={`/${locale}/features`} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-teal">{locale==='sq'?'Mëso më shumë':'Learn more'}<ArrowRight size={15}/></Link></article>})}</div></section>

    <section className="bg-[#e8f4ef]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="eyebrow">{dict.workflow.eyebrow}</p><h2 className="section-title">{dict.workflow.title}</h2></div><div className="mt-14 grid gap-y-8 sm:grid-cols-2 lg:grid-cols-7">{dict.workflow.steps.map((step,i)=><div key={step} className="relative pr-4"><div className="mb-4 flex items-center"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-teal text-sm font-semibold text-white">{i+1}</span>{i<6&&<span className="ml-2 hidden h-px w-full bg-teal/25 lg:block"/>}</div><p className="max-w-[140px] text-sm font-semibold leading-5">{step}</p></div>)}</div></div></section>

    <section id="security" className="mx-auto grid max-w-7xl items-center gap-14 px-5 py-24 lg:grid-cols-2 lg:px-8 lg:py-32"><div className="rounded-[32px] bg-ink p-7 text-white sm:p-10"><div className="mb-12 flex items-center justify-between"><span className="grid size-14 place-items-center rounded-2xl bg-white/10"><ShieldCheck size={28} className="text-[#70d6c2]"/></span><span className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/50">MEDISOFT Secure</span></div><div className="grid grid-cols-2 gap-3">{dict.security.items.map((x,i)=>{const Icon=securityIcons[i];return <div key={x} className="rounded-2xl bg-white/7 p-4"><Icon size={18} className="text-[#70d6c2]"/><p className="mt-6 text-sm font-medium">{x}</p></div>})}</div></div><div><p className="eyebrow">{dict.security.eyebrow}</p><h2 className="section-title">{dict.security.title}</h2><p className="section-copy">{dict.security.body}</p><Link href={`/${locale}/security`} className="mt-8 inline-flex items-center gap-2 font-semibold text-teal">{dict.nav.security}<MoveRight size={18}/></Link></div></section>

    <section className="mx-4 mb-4 overflow-hidden rounded-[32px] bg-teal text-white sm:mx-6"><div className="mx-auto flex max-w-5xl flex-col items-center px-5 py-20 text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-white/55">MEDISOFT</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.035em] sm:text-5xl">{dict.cta.title}</h2><p className="mt-5 max-w-xl text-white/70">{dict.cta.body}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={`/${locale}/contact`} className="rounded-full bg-white px-6 py-3.5 font-semibold text-teal">{dict.cta.primary}</Link><Link href={`/${locale}/product`} className="rounded-full border border-white/25 px-6 py-3.5 font-semibold text-white">{dict.cta.secondary}</Link></div></div></section><Footer locale={locale} dict={dict}/></main>;
}
