import Link from "next/link";
import { ArrowRight, Check, Building2, CircleDollarSign, FlaskConical, HeartPulse, Layers3, LockKeyhole, Mail, MapPin, Phone, Sparkles } from "lucide-react";
import type { Dictionary, Locale } from "@/lib/i18n";
import { Header } from "./header";
import { Footer } from "./footer";
import { DashboardPreview } from "./dashboard-preview";

const pageCopy = {
  en: {
    product:{eyebrow:"The MEDISOFT platform",title:"One place to run your clinical workflow.",body:"Keep patient context, laboratory work and final reports connected from the moment an order is created.",cards:[["Patient-first records","A complete clinical and laboratory history built around each patient."],["Guided lab workflow","Clear status, ownership and next steps for every order."],["Reliable reporting","Validated results and professional reports, ready to share."]]},
    laboratories:{eyebrow:"For laboratories",title:"Less administration. More focus on accurate results.",body:"Organize samples, workloads, validations and reports in a workspace made for the rhythm of a clinical laboratory.",cards:[["See the queue","Know what arrived, what is running and what needs validation."],["Reduce repeated work","Capture information once and carry it through the full workflow."],["Protect quality","Reference ranges, flags and controlled validation support reliable work."]]},
    clinics:{eyebrow:"For clinics",title:"A connected view of patients and laboratory care.",body:"Give reception, clinicians and laboratory teams the same clear patient context without passing paper between systems.",cards:[["Faster registration","Find returning patients quickly and keep details current."],["Clear status","Follow every order from request through final report."],["Better continuity","Previous analyses and reports stay connected to the patient."]]},
    features:{eyebrow:"Platform capabilities",title:"Practical tools for every step of the laboratory day.",body:"MEDISOFT combines patient management, order capture, sample flow, results, reporting and billing.",cards:[["Patient management","Searchable records, contacts and laboratory history."],["Orders & samples","Test selection, sample status and clear work queues."],["Results & ranges","Entry, abnormal flags, review and validation."],["Reports","Professional printable and PDF-ready results."],["Billing","Prices, payments and basic clinic billing."],["Daily oversight","Real-time workload and status visibility."]]},
    security:{eyebrow:"Security by design",title:"Access only where it belongs.",body:"MEDISOFT is designed around clear roles, traceable actions and secure access to sensitive clinical information.",cards:[["Role-based access","Permissions aligned with reception, technician and manager responsibilities."],["Activity history","Important actions stay traceable for operational accountability."],["Controlled validation","Only authorized users can validate and finalize results."],["Secure access","Encrypted connections and modern cloud security practices."]]},
    pricing:{eyebrow:"Simple, fitted pricing",title:"A plan shaped around your laboratory.",body:"Every clinic works differently. We’ll scope MEDISOFT around your locations, workflow and implementation needs.",cards:[["Clinic","Patient records, orders, results and reporting for a focused clinic workflow."],["Laboratory","Full laboratory operations with validation, reference ranges and work queues."],["Multi-site","Connected locations, centralized oversight and tailored onboarding."]]},
    about:{eyebrow:"About MEDISOFT",title:"Software should make careful work feel clearer.",body:"MEDISOFT is being built for clinics and laboratories that want a modern, approachable way to manage daily clinical operations.",cards:[["Our focus","Simple workflows that respect the precision of laboratory work."],["Our approach","Listen closely, configure thoughtfully and improve continuously."],["Our promise","A product your team can understand and trust every day."]]},
    contact:{eyebrow:"Talk to MEDISOFT",title:"Let’s understand how your laboratory works.",body:"Tell us about your clinic, team and current workflow. We’ll show you the most relevant MEDISOFT setup.",cards:[["Email","hello@medisoft.al"],["Phone","+355 69 000 0000"],["Location","Tirana, Albania"]]}
  },
  sq: {
    product:{eyebrow:"Platforma MEDISOFT",title:"Një vend për të gjithë procesin klinik.",body:"Lidhni pacientin, punën laboratorike dhe raportin final që nga krijimi i porosisë.",cards:[["Kartela e pacientit","Historiku klinik dhe laboratorik i organizuar rreth pacientit."],["Rrjedhë e udhëzuar","Status, përgjegjësi dhe hapi i ardhshëm për çdo analizë."],["Raportim i besueshëm","Rezultate të validuara dhe raporte profesionale."]]},
    laboratories:{eyebrow:"Për laboratorë",title:"Më pak administrim. Më shumë fokus te saktësia.",body:"Organizoni mostrat, ngarkesën, validimet dhe raportet në një hapësirë të krijuar për laboratorë klinikë.",cards:[["Shihni radhën","Dini çfarë ka mbërritur, çfarë po punohet dhe çfarë pret validim."],["Më pak punë e përsëritur","Vendosni të dhënat një herë dhe përdorini gjatë gjithë procesit."],["Mbroni cilësinë","Intervalet, sinjalizimet dhe validimi mbështesin punën e saktë."]]},
    clinics:{eyebrow:"Për klinika",title:"Një pamje e lidhur e pacientit dhe kujdesit laboratorik.",body:"Recepsioni, mjekët dhe laboratori punojnë me të njëjtin kontekst, pa letra mes sistemeve.",cards:[["Regjistrim më i shpejtë","Gjeni pacientët ekzistues dhe përditësoni të dhënat lehtë."],["Status i qartë","Ndiqni çdo porosi deri te raporti final."],["Vazhdimësi më e mirë","Analizat dhe raportet mbeten të lidhura me pacientin."]]},
    features:{eyebrow:"Mundësitë e platformës",title:"Mjete praktike për çdo hap të ditës laboratorike.",body:"MEDISOFT bashkon pacientët, porositë, mostrat, rezultatet, raportet dhe faturimin.",cards:[["Menaxhimi i pacientëve","Kartela të kërkueshme, kontakte dhe historik."],["Porositë dhe mostrat","Zgjedhja e testeve, statusi dhe radha e punës."],["Rezultatet dhe intervalet","Regjistrim, sinjalizim, kontroll dhe validim."],["Raportet","Rezultate profesionale për printim dhe PDF."],["Faturimi","Çmimet, pagesat dhe faturimi bazë."],["Pamja ditore","Ngarkesa dhe statusi i punës në kohë reale."]]},
    security:{eyebrow:"Siguri në themel",title:"Qasje vetëm aty ku duhet.",body:"MEDISOFT ndërtohet me role të qarta, veprime të gjurmueshme dhe qasje të sigurt në të dhënat klinike.",cards:[["Qasje sipas rolit","Leje për recepsionin, teknikun dhe drejtuesin."],["Historik veprimesh","Veprimet e rëndësishme mbeten të gjurmueshme."],["Validim i kontrolluar","Vetëm përdoruesit e autorizuar finalizojnë rezultatet."],["Qasje e sigurt","Lidhje të enkriptuara dhe praktika moderne cloud."]]},
    pricing:{eyebrow:"Çmime të përshtatura",title:"Një plan sipas laboratorit tuaj.",body:"Çdo klinikë punon ndryshe. MEDISOFT përshtatet me vendndodhjet, procesin dhe nevojat e zbatimit.",cards:[["Klinikë","Pacientë, porosi, rezultate dhe raporte për një klinikë."],["Laborator","Operacione laboratorike me validim, intervale dhe radhë pune."],["Shumë qendra","Qendra të lidhura, mbikëqyrje dhe trajnim i përshtatur."]]},
    about:{eyebrow:"Rreth MEDISOFT",title:"Teknologjia duhet ta bëjë punën e kujdesshme më të qartë.",body:"MEDISOFT po ndërtohet për klinika dhe laboratorë që kërkojnë një mënyrë moderne dhe të thjeshtë pune.",cards:[["Fokusi ynë","Proces i thjeshtë që respekton saktësinë laboratorike."],["Qasja jonë","Dëgjojmë, përshtatim dhe përmirësojmë vazhdimisht."],["Premtimi ynë","Një produkt që ekipi juaj e kupton dhe i beson."]]},
    contact:{eyebrow:"Flisni me MEDISOFT",title:"Le të kuptojmë si punon laboratori juaj.",body:"Na tregoni për klinikën, ekipin dhe procesin aktual. Do t’ju tregojmë konfigurimin më të përshtatshëm.",cards:[["Email","hello@medisoft.al"],["Telefon","+355 69 000 0000"],["Vendndodhja","Tiranë, Shqipëri"]]}
  }
} as const;

const icons = [HeartPulse, FlaskConical, Layers3, LockKeyhole, CircleDollarSign, Building2, Mail, Phone, MapPin, Sparkles];

export function InnerPage({ locale, slug, dict }: { locale: Locale; slug: keyof typeof pageCopy.en; dict: Dictionary }) {
  const content = pageCopy[locale][slug];
  const showDashboard = ["product","laboratories","clinics"].includes(slug);
  return <main className="min-h-screen bg-ivory text-ink"><Header locale={locale} dict={dict}/><section className="mx-auto max-w-7xl px-5 pb-20 pt-20 text-center lg:px-8 lg:pb-28 lg:pt-28"><p className="eyebrow">{content.eyebrow}</p><h1 className="mx-auto mt-5 max-w-4xl text-5xl font-semibold leading-[1.05] tracking-[-.045em] sm:text-6xl">{content.title}</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate">{content.body}</p><div className="mt-9 flex justify-center gap-3"><Link href={`/${locale}/contact`} className="inline-flex items-center gap-2 rounded-full bg-teal px-6 py-3.5 font-semibold text-white">{dict.hero.primary}<ArrowRight aria-hidden="true" size={17}/></Link>{slug!=="contact"&&<Link href={`/${locale}/demo`} className="rounded-full border border-line bg-white px-6 py-3.5 font-semibold">{dict.nav.demo}</Link>}</div></section>{showDashboard&&<section className="mx-auto max-w-5xl px-5 pb-24 lg:px-8"><DashboardPreview dict={dict}/></section>}<section className="border-y border-line bg-white"><div className={`mx-auto grid max-w-6xl gap-4 px-5 py-20 lg:px-8 ${content.cards.length>3?'md:grid-cols-2 lg:grid-cols-3':'md:grid-cols-3'}`}>{content.cards.map((card,i)=>{const Icon=icons[(i+(slug==="contact"?6:0))%icons.length];return <article key={card[0]} className="rounded-3xl border border-line bg-ivory p-7"><span className="grid size-11 place-items-center rounded-2xl bg-mint text-teal"><Icon aria-hidden="true" size={21}/></span><h2 className="mt-6 text-xl font-semibold">{card[0]}</h2><p className="mt-3 text-sm leading-6 text-slate">{card[1]}</p>{slug==="pricing"&&<p className="mt-8 flex items-center gap-2 text-sm font-semibold text-teal"><Check aria-hidden="true" size={16}/> Tailored onboarding</p>}</article>})}</div></section>{slug==="contact"&&<section className="mx-auto max-w-3xl px-5 py-24 text-center"><h2 className="text-3xl font-semibold">{locale==='sq'?'Gati për një demonstrim?':'Ready for a walkthrough?'}</h2><p className="mt-4 text-slate">{locale==='sq'?'Kontaktoni ekipin tonë dhe do t’ju përgjigjemi së shpejti.':'Contact our team and we’ll get back to you shortly.'}</p><a href="mailto:hello@medisoft.al" className="mt-8 inline-flex rounded-full bg-ink px-7 py-3.5 font-semibold text-white">hello@medisoft.al</a></section>}<Footer locale={locale} dict={dict}/></main>;
}
